# Generated by Django 3.1.5 on 2021-02-16 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Covid',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('SEXO', models.IntegerField(choices=[(1, 'Femenino'), (0, 'Masculino')])),
                ('EDAD', models.IntegerField()),
                ('NEUMONIA', models.IntegerField(choices=[(1, 'Si'), (0, 'No')], default=0)),
                ('DIABETES', models.IntegerField(choices=[(1, 'Si'), (0, 'No')], default=0)),
                ('EPOC', models.IntegerField(choices=[(1, 'Si'), (0, 'No')], default=0)),
                ('ASMA', models.IntegerField(choices=[(1, 'Si'), (0, 'No')], default=0)),
                ('INMUSUPR', models.IntegerField(choices=[(1, 'Si'), (0, 'No')], default=0)),
                ('HIPERTENSION', models.IntegerField(choices=[(1, 'Si'), (0, 'No')], default=0)),
                ('CARDIOVASCULAR', models.IntegerField(choices=[(1, 'Si'), (0, 'No')], default=0)),
                ('OBESIDAD', models.IntegerField(choices=[(1, 'Si'), (0, 'No')], default=0)),
                ('RENAL_CRONICA', models.IntegerField(choices=[(1, 'Si'), (0, 'No')], default=0)),
                ('TABAQUISMO', models.IntegerField(choices=[(1, 'Si'), (0, 'No')], default=0)),
                ('COVID', models.IntegerField(choices=[(1, 'Si'), (0, 'No')], default=0)),
                ('OTRA_COM', models.IntegerField(choices=[(1, 'Si'), (0, 'No')], default=0)),
                ('DECESO', models.IntegerField()),
            ],
        ),
    ]
